---
title: "Project 2"
author: "SDS348 Fall 2019"
date: "10/20/2019"
output:
  html_document: default
  pdf_document: default
---

## Alexa D. Reyna-Carrillo adr2872

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```


```{R}
library("survival")
library("ggplot2")
library("tidyverse")
data("veteran")
```

### 0 - Introduction:

*The dataset I will be using is the veteran dataset found on the 'survival' package. This data focuses on a veterans' administration lung cancer study. There was a randomized trial of two treatment regimens for lung cancer performed in veterans, and the standard survival analysis was collected to create the dataset. The dataset contains 137 observations and 8 columns/variables. The variables for this dataset are treatment, celltype, time, status, Karnofsky score, diagnosis time, age, and prior therapy. Treatment is a binary variable consisting on what type of treatment the veterans received, whether standard or test. The celltype is a categorical variable that determined which carcinoma cell the treatment targeted. The time variable is a numeric variable that calculated the cells' survival time. Status is a binary variable that described whether it was censored or not. Karno is a numeric variable that collected the veterans' Karnofsky performance score from 0 to 100. Diagtime is another numeric variable that shows the months from diagnosis to randomization. Age is a numeric variable calculated in years to know the veterans' age. Lastly, prior is a binary variable that determined whether the veterans had prior therapy or not. *

### 1 - MANOVA:

```{R}
man1 <- manova(cbind(time, age)~celltype, data=veteran)
summary(man1)
summary.aov(man1)
pairwise.t.test(veteran$time, veteran$celltype, p.adj="none")
1-(0.95^7)
0.05/7
```

*There were 7 tests performed. The MANOVA test was performed to determine the effect of the celltype categorical variable containing 4 levels (squamous, smallcell, adeno, and large) on two numeric variables (age and time). The probability of at least one Type I error was 0.30 and using the Bonferroni method, the adjusted significance level was 0.007. Because the MANOVA demonstrated that at least one of the numeric variables showed a signicant mean difference on the 4 cell type levels, 2 ANOVAs were then performed to determine which of the two had a significant mean difference. The univariate ANOVA of time showed a significant mean difference across the 4 levels while the ANOVA of age did not. Post hoc analysis was performed conducting 4 pairwise comparisons to determine which cell type differed in time. Therefore, only the squamous cell type was found to differ significantly in terms of time after adjusting for multiple comparisons (Bonferroni). The MANOVA assumptions of random sampling/independent observations, multivariate normality of dependent variables (DVs), homogeneity of within-group covariance matrices, and no multicollinearity are likely to be met. The assumption of linear relationships among DVs, however, is likely to not be met due to the missing linear relationship between age and time variables. The assumption of no extreme univariate or multivariate outliers is also likely to not be met due to the drastic differences in responses on the time variable ranging from 1 to 999.*

### 2 - Randomization test: 

```{R}
library(vegan)
dists <- vegdist(sqrt(veteran[,-c(2,3,7)]), method = "bray")
distSq <- vegdist(sqrt(veteran[veteran$celltype == "squamous", -c(2,3,7)]), method = "bray")
distSm <- vegdist(sqrt(veteran[veteran$celltype == "smallcell", -c(2,3,7)]), method = "bray")
distAd <- vegdist(sqrt(veteran[veteran$celltype == "adeno", -c(2,3,7)]), method = "bray")
distLa <- vegdist(sqrt(veteran[veteran$celltype == "large", -c(2,3,7)]), method = "bray")
SSR <- sum(distSq^2)/35 + sum(distSm^2)/48 + sum(distAd^2)/27 + sum(distLa^2)/27
SST <- sum(dists^2)/137
Fstat <- (SST - SSR)/(SSR/134)
Fstat

perm.sampdist<-replicate(5000,{
new<-veteran
new$celltype<-sample(veteran$celltype)
dists<-vegdist(sqrt(new[,-c(2,3,7)]),method="bray")
distSq<-vegdist(sqrt(new[new$celltype=="squamous",-c(2,3,7)]),method="bray")
distSm<-vegdist(sqrt(new[new$celltype=="smallcell",-c(2,3,7)]),method="bray")
distAd<-vegdist(sqrt(new[new$celltype=="adeno",-c(2,3,7)]),method="bray")
distLa<-vegdist(sqrt(new[new$celltype=="large",-c(2,3,7)]),method="bray")
SSR <- sum(distSq^2)/35 + sum(distSm^2)/48 + sum(distAd^2)/27 + sum(distLa^2)/27
SST <- sum(dists^2)/137
(SST-SSR)/(SSR/134)
} )

mean(perm.sampdist>Fstat)

{hist(perm.sampdist,prob = T); abline(v=Fstat, col="red", add=T)}
```

*The randomization test that was performed on the data was a PERMANOVA test. The null hypothesis is: For age and time, the means of each cell type are equal. The alternative hypothesis is: For at least one of the dependent variables, at least one cell type mean is different. After the test was performed, it was determined that the actual F statistic is far away from the majority of the F statistics that arise in the simulation distribution where there is no difference between groups, indicating that there is enough evidence to say that age and time differ between those groups. The results demonstrated that 7.3% of the simulated sampling distribution is greater than our observed F-stat. Since this distribution was created under the null hypothesis of no mean difference between groups, there is a 7% chance of seeing an F-stat this large under the null, so we cannot reject this hypothesis as inconsistent with our data.*

### 3 - Linear regression model: 

```{R}
library(sandwich)
library(lmtest)
veteran <- veteran %>% mutate("karno_c" = scale(veteran$karno, center = TRUE, scale = FALSE)) %>% mutate("time_c" = scale(veteran$time, center = TRUE, scale = FALSE)) %>% mutate("age_c" = scale(veteran$time, center = TRUE, scale = FALSE)) %>% mutate("diagtime_c" = scale(veteran$diagtime, center = TRUE, scale = FALSE))

fit<-lm(time ~ celltype * diagtime_c, data=veteran)
coeftest(fit)

newdat<-veteran
newdat$celltype<-rep("squamous",length(newdat$celltype))
newdat$pred1<-predict(fit,newdat)
newdat$celltype<-rep("smallcell",length(newdat$celltype))
newdat$pred2<-predict(fit,newdat)
newdat$celltype<-rep("adeno",length(newdat$celltype))
newdat$pred3<-predict(fit,newdat)
newdat$celltype<-rep("large",length(newdat$celltype))
newdat$pred4<-predict(fit,newdat)

ggplot(veteran, aes(x = diagtime_c, y = time)) + geom_point() + geom_line(data = newdat, aes(y = pred1),color='blue' ) + geom_line(data = newdat, aes(y = pred2),color='red' ) + geom_line(data = newdat, aes(y = pred3),color='purple' ) + geom_line(data = newdat, aes(y = pred4),color='orange' )

resids<-fit$residuals
fitvals<-fit$fitted.values 
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color='red')
bptest(fit)
ggplot()+geom_histogram(aes(resids), bins=20)
shapiro.test(resids)
summary(fit)$coef[,1:2]
coeftest(fit, vcov = vcovHC(fit))[,1:2]
(sum((veteran$time-mean(veteran$time))^2)-sum(fit$residuals^2))/sum((veteran$time-mean(veteran$time))^2)   
```

*A linear regression model was performed to predict the survival time (time) from cell type (celltype) and diagnosis time (diagtime), including their interaction. For the interaction, there was only one numeric variable (diagnosis time) which was mean centered for better accuracy. The full model with the interaction is time = 210.64 - 139.11 (celltypesmallcell) - 150.39(celltypeadeno) - 45.26(celltypelarge) - 4.63(diagtime_c) + 4.92(celltypesmallcell x diagtime_c) + 3.40(celltypeadeno x diagtime_c) + 3.47(celltypelarge x diagtime_c). Controlling for diagtime_c, when celltypesmallcell is 1 and the other cell type levels are 0, time decreases by a factor of 139.11. Controlling for diagtime_c, when celltypeadeno is 1 and the other cell type levels are 0, time decreases by a factor of 150.39. Controlling for diagtime_c, when celltypelarge is 1 and the other cell type levels are 0, time decreases by a factor of 45.26. For every 1-unit increase in diagtime_c, time decreases by a factor of 4.63, on average. For the interaction where the small cell is 1, and the other cell types are 0, resulting equation is 210.64 -139.11 - 4.63(diagtime_c) + 4.92(1xdiagtime_c) =  71.53 + 0.29(diagtime_c). For the interaction where the adeno cell is 1, and the other cell types are 0, resulting equation is 210.64 - 150.39 - 4.63(diagtime_c) + 3.40(1xdiagtime_c) = 60.25 - 1.23(diagtime_c). For the interaction where the large cell is 1, and the other cell types are 0, resulting equation is 210.64 - 45.26 + 4.63(diagtime_c) + 3.47(1xdiagtime_c) = 165.38 + 8.10(diagtime_c). The estimate for the interaction term is the difference in the slopes. The significance of the results is to run robust standard errors to determine whether the heteroskedastic plot has proper standard errors (SEs) to justify the assumption of skedasticity of the graph. The results show that the graph is in fact, heteroskedastic because of the changes in robust SEs before and afer recomputing the regression. The changes in SEs from uncorrected to corrected increase for all of the predictors except for diagtime_c and all of the interactions between cell type and diagtime_c (celltypesmallcell:diagtime_c, celltypeadeno:diagtime_c, and celltypelarge:diagtime_c), meaning that the homoskedasticity assumption was violated. A proportion of 0.17 was calculated to explain the variation in the response variable of time explained by the overall model.*

### 4 - Linear regression model (cont.): 

```{R}
bptest(fit)

x=seq(-5,5,length.out=1000)
y=1+2*x+rnorm(1000)
dat<-data.frame(x,y)

boot_dat<-dat[sample(nrow(dat),replace=TRUE),]
samp_distn<-replicate(5000, {
 boot_dat<-veteran[sample(nrow(veteran),replace=TRUE),]
 fit<-lm(time~celltype*diagtime_c,data=boot_dat)
 coef(fit)
})
samp_distn%>%t%>%as.data.frame%>%summarize_all(sd)
```

*The same regression model (with the interaction), but with bootstrappped standard errors was then performed to observe and compare the SEs and p-values to the original and robust SEs. The original SEs are very different from the bootstrapped SEs for the cell type levels but are similar for diagtime_c and the interactions (celltypesmallcell:diagtime_c, celltypeadeno:diagtime_c, and celltypelarge:diagtime_c). However, the bootstrapped SEs are almost the same as the robust SEs, only differing from decimals to one point. The p-value for the interaction model was 0.09391.*

### 5 - Logistic regression model:

```{R}
veteran <- veteran %>% transmute( trt, celltype, time, status, karno, diagtime, age, prior, y=as.numeric(ifelse(prior == "10",1,0)))
fit1<-glm(y ~  celltype + diagtime , data=veteran,family="binomial")
coeftest(fit1)
exp(coef(fit1))
prob<-predict(fit1,type="response")
pred<-ifelse(prob>.5,1,0)
table(truth=veteran$y,prediction=pred)%>%addmargins
(92+14)/137 #accuracy
14/40 #tpr
92/97 #tnr
14/19 #ppv

odds<-function(p)p/(1-p)
p<-seq(0,1,by=.1)
cbind(p, odds=odds(p))%>%round(4)
logit<-function(p)log(odds(p))
cbind(p, odds=odds(p),logit=logit(p))%>%round(4)

veteran$logit<-predict(fit1)
veteran$y<-factor(veteran$y,levels=c("1","0"))
ggplot(veteran,aes(logit, fill=y))+geom_density(alpha=.3)+
geom_vline(xintercept=0,lty=2)

library(plotROC) 
veteran <- veteran %>% transmute( trt, celltype, time, status, karno, diagtime, age, prior, y=as.numeric(ifelse(prior == "10",1,0)))
ROCplot<-ggplot(veteran)+geom_roc(aes(d=y,m=prob), n.cuts=0) 
ROCplot
calc_auc(ROCplot)

class_diag<-function(probs,truth){
 tab<-table(factor(probs>.5,levels=c("FALSE","TRUE")),truth)
 acc=sum(diag(tab))/sum(tab)
 sens=tab[2,2]/colSums(tab)[2]
 spec=tab[1,1]/colSums(tab)[1]
 ppv=tab[2,2]/rowSums(tab)[2]
 if(is.numeric(truth)==FALSE & is.logical(truth)==FALSE) truth<-as.numeric(truth)-1
 ord<-order(probs, decreasing=TRUE)
 probs <- probs[ord]; truth <- truth[ord]
 TPR=cumsum(truth)/max(1,sum(truth))
 FPR=cumsum(!truth)/max(1,sum(!truth))
 dup<-c(probs[-1]>=probs[-length(probs)], FALSE)
 TPR<-c(0,TPR[!dup],1); FPR<-c(0,FPR[!dup],1)
 n <- length(TPR)
 auc<- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
 data.frame(acc,sens,spec,ppv,auc)
} 

set.seed(1234)
k=10 
data1<-veteran[sample(nrow(veteran)),]
folds<-cut(seq(1:nrow(veteran)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
 train<-data1[folds!=i,]
 test<-data1[folds==i,]
 truth<-test$y
 fit<-glm(y~celltype + diagtime,data=train,family="binomial")
 probs<-predict(fit,newdata = test,type="response")
 diags<-rbind(diags,class_diag(probs,truth))
}
apply(diags,2,mean)
```

*A logistic regression was performed on to predict the prior therapy variable (y) from the variables of cell type (celltype) and diagnosis time (diagtime). After running the coefficient test, the diagnosis time significantly increases the log-odds of prior therapy observed (y = 1). Controlling for diagnosis time (diagtime), none of the cell types, including squamous, are significantly different. Controlling for cell type (celltype), for every 1-unit increase in diagnosis time (diagtime), odds of prior therapy change by a factor of 1.149 (increasing by 114%). A confusion matrix for the logistic regression was performed to plot model predictions against true values. The proportion of correctly classified cases is the overall accuracy resulting in a value of 0.77. The sensitivity (TPR) values is 0.35, meaning that was the proportion of prior therapy (y = 1) correctly classified. The correctly classified proportion, or specificity (TNR) of no prior therapy (y = 0) is 0.95. The proportion classified as having prior therapy (y = 1) who actually are classified is 0.74. An ROC curve was generated to then calculate the AUC, which is the area under the curve. The purpose of calculating the AUC was to quantify how well the predictions are overall.The AUC that was calculated resulted in a value of 0.814. Because the AUC falls between .8-.9, the AUC value is considered good. The 10-fold CV was performed and the average out-of-sample accuracy is 0.75, average out-of-sample sensitivity is 0.37, and there was not an average out-of-sample recall (ppv = NaN).  *

### 6 - LASSO regression model: 

```{R}
library(glmnet)
fit2 <- glm(y ~ -1 + status + karno + time + celltype + diagtime + age + trt, data = veteran, family = "binomial")
model.matrix(fit2) %>% head()
set.seed(1234)
x<-model.matrix(fit2)
x<-scale(x)
y<-as.matrix(veteran$y)
cv<-cv.glmnet(x,y,family='binomial')
lasso<-glmnet(x,y,family='binomial',lambda=cv$lambda.1se)
coef(cv)

set.seed(1234)
k=10
data1<-veteran[sample(nrow(veteran)),]
folds<-cut(seq(1:nrow(veteran)),breaks=k,labels=F)
diags<-NULL
for(i in 1:k){
 train<-data1[folds!=i,]
 test<-data1[folds==i,]
 truth<-test$y
 fit3<-glm(y~diagtime,data=train,family="binomial")
 probs<-predict(fit3,newdata = test,type="response")
 diags<-rbind(diags,class_diag(probs,truth))
}
diags%>%summarize_all(mean)

```

*After the LASSO regression was performed and choosing lambda to give the simplest model whose accuracy is near that of the best, the variable retained was the diagnosis time (diagtime). This is the most important predictors of y.Once the 10-fold CV model was performed, the model's out-of-sample accuracy is the same as that of the logistic regression in part 5, both with a value of 0.75. *



