---
title: "Project 2"
author: "SDS348 Fall 2019"
date: "2019-12-16"
output:
  html_document: default
  pdf_document: default
---



<div id="alexa-d.-reyna-carrillo-adr2872" class="section level2">
<h2>Alexa D. Reyna-Carrillo adr2872</h2>
<pre class="r"><code>library(&quot;survival&quot;)
library(&quot;ggplot2&quot;)
library(&quot;tidyverse&quot;)</code></pre>
<pre><code>## ── Attaching packages ────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ tibble  2.1.3     ✓ dplyr   0.8.3
## ✓ tidyr   1.0.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.4.0
## ✓ purrr   0.3.3</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>data(&quot;veteran&quot;)</code></pre>
<div id="introduction" class="section level3">
<h3>0 - Introduction:</h3>
<p><em>The dataset I will be using is the veteran dataset found on the ‘survival’ package. This data focuses on a veterans’ administration lung cancer study. There was a randomized trial of two treatment regimens for lung cancer performed in veterans, and the standard survival analysis was collected to create the dataset. The dataset contains 137 observations and 8 columns/variables. The variables for this dataset are treatment, celltype, time, status, Karnofsky score, diagnosis time, age, and prior therapy. Treatment is a binary variable consisting on what type of treatment the veterans received, whether standard or test. The celltype is a categorical variable that determined which carcinoma cell the treatment targeted. The time variable is a numeric variable that calculated the cells’ survival time. Status is a binary variable that described whether it was censored or not. Karno is a numeric variable that collected the veterans’ Karnofsky performance score from 0 to 100. Diagtime is another numeric variable that shows the months from diagnosis to randomization. Age is a numeric variable calculated in years to know the veterans’ age. Lastly, prior is a binary variable that determined whether the veterans had prior therapy or not. </em></p>
</div>
<div id="manova" class="section level3">
<h3>1 - MANOVA:</h3>
<pre class="r"><code>man1 &lt;- manova(cbind(time, age)~celltype, data=veteran)
summary(man1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df   Pr(&gt;F)   
## celltype    3 0.15642   3.7614      6    266 0.001303 **
## Residuals 133                                           
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response time :
##              Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## celltype      3  478636  159545  7.2955 0.0001446 ***
## Residuals   133 2908596   21869                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response age :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## celltype      3    258  86.001    0.77 0.5128
## Residuals   133  14855 111.693</code></pre>
<pre class="r"><code>pairwise.t.test(veteran$time, veteran$celltype, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  veteran$time and veteran$celltype 
## 
##           squamous smallcell adeno  
## smallcell 0.00015  -         -      
## adeno     0.00046  0.83213   -      
## large     0.36977  0.00890   0.01243
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1-(0.95^7)</code></pre>
<pre><code>## [1] 0.3016627</code></pre>
<pre class="r"><code>0.05/7</code></pre>
<pre><code>## [1] 0.007142857</code></pre>
<p><em>There were 7 tests performed. The MANOVA test was performed to determine the effect of the celltype categorical variable containing 4 levels (squamous, smallcell, adeno, and large) on two numeric variables (age and time). The probability of at least one Type I error was 0.30 and using the Bonferroni method, the adjusted significance level was 0.007. Because the MANOVA demonstrated that at least one of the numeric variables showed a signicant mean difference on the 4 cell type levels, 2 ANOVAs were then performed to determine which of the two had a significant mean difference. The univariate ANOVA of time showed a significant mean difference across the 4 levels while the ANOVA of age did not. Post hoc analysis was performed conducting 4 pairwise comparisons to determine which cell type differed in time. Therefore, only the squamous cell type was found to differ significantly in terms of time after adjusting for multiple comparisons (Bonferroni). The MANOVA assumptions of random sampling/independent observations, multivariate normality of dependent variables (DVs), homogeneity of within-group covariance matrices, and no multicollinearity are likely to be met. The assumption of linear relationships among DVs, however, is likely to not be met due to the missing linear relationship between age and time variables. The assumption of no extreme univariate or multivariate outliers is also likely to not be met due to the drastic differences in responses on the time variable ranging from 1 to 999.</em></p>
</div>
<div id="randomization-test" class="section level3">
<h3>2 - Randomization test:</h3>
<pre class="r"><code>library(vegan)</code></pre>
<pre><code>## Loading required package: permute</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## This is vegan 2.5-6</code></pre>
<pre class="r"><code>dists &lt;- vegdist(sqrt(veteran[,-c(2,3,7)]), method = &quot;bray&quot;)
distSq &lt;- vegdist(sqrt(veteran[veteran$celltype == &quot;squamous&quot;, -c(2,3,7)]), method = &quot;bray&quot;)
distSm &lt;- vegdist(sqrt(veteran[veteran$celltype == &quot;smallcell&quot;, -c(2,3,7)]), method = &quot;bray&quot;)
distAd &lt;- vegdist(sqrt(veteran[veteran$celltype == &quot;adeno&quot;, -c(2,3,7)]), method = &quot;bray&quot;)
distLa &lt;- vegdist(sqrt(veteran[veteran$celltype == &quot;large&quot;, -c(2,3,7)]), method = &quot;bray&quot;)
SSR &lt;- sum(distSq^2)/35 + sum(distSm^2)/48 + sum(distAd^2)/27 + sum(distLa^2)/27
SST &lt;- sum(dists^2)/137
Fstat &lt;- (SST - SSR)/(SSR/134)
Fstat</code></pre>
<pre><code>## [1] 6.788443</code></pre>
<pre class="r"><code>perm.sampdist&lt;-replicate(5000,{
new&lt;-veteran
new$celltype&lt;-sample(veteran$celltype)
dists&lt;-vegdist(sqrt(new[,-c(2,3,7)]),method=&quot;bray&quot;)
distSq&lt;-vegdist(sqrt(new[new$celltype==&quot;squamous&quot;,-c(2,3,7)]),method=&quot;bray&quot;)
distSm&lt;-vegdist(sqrt(new[new$celltype==&quot;smallcell&quot;,-c(2,3,7)]),method=&quot;bray&quot;)
distAd&lt;-vegdist(sqrt(new[new$celltype==&quot;adeno&quot;,-c(2,3,7)]),method=&quot;bray&quot;)
distLa&lt;-vegdist(sqrt(new[new$celltype==&quot;large&quot;,-c(2,3,7)]),method=&quot;bray&quot;)
SSR &lt;- sum(distSq^2)/35 + sum(distSm^2)/48 + sum(distAd^2)/27 + sum(distLa^2)/27
SST &lt;- sum(dists^2)/137
(SST-SSR)/(SSR/134)
} )

mean(perm.sampdist&gt;Fstat)</code></pre>
<pre><code>## [1] 0.0376</code></pre>
<pre class="r"><code>{hist(perm.sampdist,prob = T); abline(v=Fstat, col=&quot;red&quot;, add=T)}</code></pre>
<pre><code>## Warning in int_abline(a = a, b = b, h = h, v = v, untf = untf, ...): &quot;add&quot; is
## not a graphical parameter</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p><em>The randomization test that was performed on the data was a PERMANOVA test. The null hypothesis is: For age and time, the means of each cell type are equal. The alternative hypothesis is: For at least one of the dependent variables, at least one cell type mean is different. After the test was performed, it was determined that the actual F statistic is far away from the majority of the F statistics that arise in the simulation distribution where there is no difference between groups, indicating that there is enough evidence to say that age and time differ between those groups. The results demonstrated that 7.3% of the simulated sampling distribution is greater than our observed F-stat. Since this distribution was created under the null hypothesis of no mean difference between groups, there is a 7% chance of seeing an F-stat this large under the null, so we cannot reject this hypothesis as inconsistent with our data.</em></p>
</div>
<div id="linear-regression-model" class="section level3">
<h3>3 - Linear regression model:</h3>
<pre class="r"><code>library(sandwich)
library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>veteran &lt;- veteran %&gt;% mutate(&quot;karno_c&quot; = scale(veteran$karno, center = TRUE, scale = FALSE)) %&gt;% mutate(&quot;time_c&quot; = scale(veteran$time, center = TRUE, scale = FALSE)) %&gt;% mutate(&quot;age_c&quot; = scale(veteran$time, center = TRUE, scale = FALSE)) %&gt;% mutate(&quot;diagtime_c&quot; = scale(veteran$diagtime, center = TRUE, scale = FALSE))

fit&lt;-lm(time ~ celltype * diagtime_c, data=veteran)
coeftest(fit)</code></pre>
<pre><code>## 
## t test of coefficients:
## 
##                               Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)                   210.6406    25.4301  8.2831 1.327e-13 ***
## celltypesmallcell            -139.1122    33.1800 -4.1927 5.084e-05 ***
## celltypeadeno                -150.3905    42.6369 -3.5272 0.0005823 ***
## celltypelarge                 -45.2576    38.2935 -1.1819 0.2394352    
## diagtime_c                     -4.6303     2.1952 -2.1093 0.0368530 *  
## celltypesmallcell:diagtime_c    4.9206     2.6859  1.8321 0.0692493 .  
## celltypeadeno:diagtime_c        3.4023     6.4583  0.5268 0.5992315    
## celltypelarge:diagtime_c        3.4665     6.2012  0.5590 0.5771291    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>newdat&lt;-veteran
newdat$celltype&lt;-rep(&quot;squamous&quot;,length(newdat$celltype))
newdat$pred1&lt;-predict(fit,newdat)
newdat$celltype&lt;-rep(&quot;smallcell&quot;,length(newdat$celltype))
newdat$pred2&lt;-predict(fit,newdat)
newdat$celltype&lt;-rep(&quot;adeno&quot;,length(newdat$celltype))
newdat$pred3&lt;-predict(fit,newdat)
newdat$celltype&lt;-rep(&quot;large&quot;,length(newdat$celltype))
newdat$pred4&lt;-predict(fit,newdat)

ggplot(veteran, aes(x = diagtime_c, y = time)) + geom_point() + geom_line(data = newdat, aes(y = pred1),color=&#39;blue&#39; ) + geom_line(data = newdat, aes(y = pred2),color=&#39;red&#39; ) + geom_line(data = newdat, aes(y = pred3),color=&#39;purple&#39; ) + geom_line(data = newdat, aes(y = pred4),color=&#39;orange&#39; )</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values 
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 12.209, df = 7, p-value = 0.09391</code></pre>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<pre class="r"><code>shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.77282, p-value = 2.723e-13</code></pre>
<pre class="r"><code>summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                                 Estimate Std. Error
## (Intercept)                   210.640630  25.430072
## celltypesmallcell            -139.112242  33.179968
## celltypeadeno                -150.390492  42.636914
## celltypelarge                 -45.257554  38.293491
## diagtime_c                     -4.630301   2.195204
## celltypesmallcell:diagtime_c    4.920635   2.685850
## celltypeadeno:diagtime_c        3.402293   6.458314
## celltypelarge:diagtime_c        3.466514   6.201249</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                                 Estimate Std. Error
## (Intercept)                   210.640630  43.522600
## celltypesmallcell            -139.112242  45.352812
## celltypeadeno                -150.390492  46.094332
## celltypelarge                 -45.257554  49.576922
## diagtime_c                     -4.630301   1.612375
## celltypesmallcell:diagtime_c    4.920635   2.069727
## celltypeadeno:diagtime_c        3.402293   3.429126
## celltypelarge:diagtime_c        3.466514   5.495458</code></pre>
<pre class="r"><code>(sum((veteran$time-mean(veteran$time))^2)-sum(fit$residuals^2))/sum((veteran$time-mean(veteran$time))^2)   </code></pre>
<pre><code>## [1] 0.1706571</code></pre>
<p><em>A linear regression model was performed to predict the survival time (time) from cell type (celltype) and diagnosis time (diagtime), including their interaction. For the interaction, there was only one numeric variable (diagnosis time) which was mean centered for better accuracy. The full model with the interaction is time = 210.64 - 139.11 (celltypesmallcell) - 150.39(celltypeadeno) - 45.26(celltypelarge) - 4.63(diagtime_c) + 4.92(celltypesmallcell x diagtime_c) + 3.40(celltypeadeno x diagtime_c) + 3.47(celltypelarge x diagtime_c). Controlling for diagtime_c, when celltypesmallcell is 1 and the other cell type levels are 0, time decreases by a factor of 139.11. Controlling for diagtime_c, when celltypeadeno is 1 and the other cell type levels are 0, time decreases by a factor of 150.39. Controlling for diagtime_c, when celltypelarge is 1 and the other cell type levels are 0, time decreases by a factor of 45.26. For every 1-unit increase in diagtime_c, time decreases by a factor of 4.63, on average. For the interaction where the small cell is 1, and the other cell types are 0, resulting equation is 210.64 -139.11 - 4.63(diagtime_c) + 4.92(1xdiagtime_c) = 71.53 + 0.29(diagtime_c). For the interaction where the adeno cell is 1, and the other cell types are 0, resulting equation is 210.64 - 150.39 - 4.63(diagtime_c) + 3.40(1xdiagtime_c) = 60.25 - 1.23(diagtime_c). For the interaction where the large cell is 1, and the other cell types are 0, resulting equation is 210.64 - 45.26 + 4.63(diagtime_c) + 3.47(1xdiagtime_c) = 165.38 + 8.10(diagtime_c). The estimate for the interaction term is the difference in the slopes. The significance of the results is to run robust standard errors to determine whether the heteroskedastic plot has proper standard errors (SEs) to justify the assumption of skedasticity of the graph. The results show that the graph is in fact, heteroskedastic because of the changes in robust SEs before and afer recomputing the regression. The changes in SEs from uncorrected to corrected increase for all of the predictors except for diagtime_c and all of the interactions between cell type and diagtime_c (celltypesmallcell:diagtime_c, celltypeadeno:diagtime_c, and celltypelarge:diagtime_c), meaning that the homoskedasticity assumption was violated. A proportion of 0.17 was calculated to explain the variation in the response variable of time explained by the overall model.</em></p>
</div>
<div id="linear-regression-model-cont." class="section level3">
<h3>4 - Linear regression model (cont.):</h3>
<pre class="r"><code>bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 12.209, df = 7, p-value = 0.09391</code></pre>
<pre class="r"><code>x=seq(-5,5,length.out=1000)
y=1+2*x+rnorm(1000)
dat&lt;-data.frame(x,y)

boot_dat&lt;-dat[sample(nrow(dat),replace=TRUE),]
samp_distn&lt;-replicate(5000, {
 boot_dat&lt;-veteran[sample(nrow(veteran),replace=TRUE),]
 fit&lt;-lm(time~celltype*diagtime_c,data=boot_dat)
 coef(fit)
})
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>##   (Intercept) celltypesmallcell celltypeadeno celltypelarge diagtime_c
## 1    43.81563          45.59197      45.86374      49.37229   2.393429
##   celltypesmallcell:diagtime_c celltypeadeno:diagtime_c
## 1                     2.796472                 3.512894
##   celltypelarge:diagtime_c
## 1                 5.495349</code></pre>
<p><em>The same regression model (with the interaction), but with bootstrappped standard errors was then performed to observe and compare the SEs and p-values to the original and robust SEs. The original SEs are very different from the bootstrapped SEs for the cell type levels but are similar for diagtime_c and the interactions (celltypesmallcell:diagtime_c, celltypeadeno:diagtime_c, and celltypelarge:diagtime_c). However, the bootstrapped SEs are almost the same as the robust SEs, only differing from decimals to one point. The p-value for the interaction model was 0.09391.</em></p>
</div>
<div id="logistic-regression-model" class="section level3">
<h3>5 - Logistic regression model:</h3>
<pre class="r"><code>veteran &lt;- veteran %&gt;% transmute( trt, celltype, time, status, karno, diagtime, age, prior, y=as.numeric(ifelse(prior == &quot;10&quot;,1,0)))
fit1&lt;-glm(y ~  celltype + diagtime , data=veteran,family=&quot;binomial&quot;)
coeftest(fit1)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                    Estimate Std. Error z value  Pr(&gt;|z|)    
## (Intercept)       -1.821480   0.498894 -3.6510 0.0002612 ***
## celltypesmallcell -0.773749   0.569471 -1.3587 0.1742368    
## celltypeadeno     -0.559333   0.660995 -0.8462 0.3974421    
## celltypelarge      0.098320   0.576221  0.1706 0.8645157    
## diagtime           0.139756   0.033946  4.1170 3.838e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit1))</code></pre>
<pre><code>##       (Intercept) celltypesmallcell     celltypeadeno     celltypelarge 
##         0.1617861         0.4612807         0.5715903         1.1033156 
##          diagtime 
##         1.1499926</code></pre>
<pre class="r"><code>prob&lt;-predict(fit1,type=&quot;response&quot;)
pred&lt;-ifelse(prob&gt;.5,1,0)
table(truth=veteran$y,prediction=pred)%&gt;%addmargins</code></pre>
<pre><code>##      prediction
## truth   0   1 Sum
##   0    92   5  97
##   1    26  14  40
##   Sum 118  19 137</code></pre>
<pre class="r"><code>(92+14)/137 #accuracy</code></pre>
<pre><code>## [1] 0.7737226</code></pre>
<pre class="r"><code>14/40 #tpr</code></pre>
<pre><code>## [1] 0.35</code></pre>
<pre class="r"><code>92/97 #tnr</code></pre>
<pre><code>## [1] 0.9484536</code></pre>
<pre class="r"><code>14/19 #ppv</code></pre>
<pre><code>## [1] 0.7368421</code></pre>
<pre class="r"><code>odds&lt;-function(p)p/(1-p)
p&lt;-seq(0,1,by=.1)
cbind(p, odds=odds(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds
##  [1,] 0.0 0.0000
##  [2,] 0.1 0.1111
##  [3,] 0.2 0.2500
##  [4,] 0.3 0.4286
##  [5,] 0.4 0.6667
##  [6,] 0.5 1.0000
##  [7,] 0.6 1.5000
##  [8,] 0.7 2.3333
##  [9,] 0.8 4.0000
## [10,] 0.9 9.0000
## [11,] 1.0    Inf</code></pre>
<pre class="r"><code>logit&lt;-function(p)log(odds(p))
cbind(p, odds=odds(p),logit=logit(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds   logit
##  [1,] 0.0 0.0000    -Inf
##  [2,] 0.1 0.1111 -2.1972
##  [3,] 0.2 0.2500 -1.3863
##  [4,] 0.3 0.4286 -0.8473
##  [5,] 0.4 0.6667 -0.4055
##  [6,] 0.5 1.0000  0.0000
##  [7,] 0.6 1.5000  0.4055
##  [8,] 0.7 2.3333  0.8473
##  [9,] 0.8 4.0000  1.3863
## [10,] 0.9 9.0000  2.1972
## [11,] 1.0    Inf     Inf</code></pre>
<pre class="r"><code>veteran$logit&lt;-predict(fit1)
veteran$y&lt;-factor(veteran$y,levels=c(&quot;1&quot;,&quot;0&quot;))
ggplot(veteran,aes(logit, fill=y))+geom_density(alpha=.3)+
geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>library(plotROC) 
veteran &lt;- veteran %&gt;% transmute( trt, celltype, time, status, karno, diagtime, age, prior, y=as.numeric(ifelse(prior == &quot;10&quot;,1,0)))
ROCplot&lt;-ggplot(veteran)+geom_roc(aes(d=y,m=prob), n.cuts=0) 
ROCplot</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8136598</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
 tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
 acc=sum(diag(tab))/sum(tab)
 sens=tab[2,2]/colSums(tab)[2]
 spec=tab[1,1]/colSums(tab)[1]
 ppv=tab[2,2]/rowSums(tab)[2]
 if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
 ord&lt;-order(probs, decreasing=TRUE)
 probs &lt;- probs[ord]; truth &lt;- truth[ord]
 TPR=cumsum(truth)/max(1,sum(truth))
 FPR=cumsum(!truth)/max(1,sum(!truth))
 dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
 TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
 n &lt;- length(TPR)
 auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
 data.frame(acc,sens,spec,ppv,auc)
} 

set.seed(1234)
k=10 
data1&lt;-veteran[sample(nrow(veteran)),]
folds&lt;-cut(seq(1:nrow(veteran)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$y
 fit&lt;-glm(y~celltype + diagtime,data=train,family=&quot;binomial&quot;)
 probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
 diags&lt;-rbind(diags,class_diag(probs,truth))
}
apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.7445055 0.3242857 0.9125253       NaN 0.7890876</code></pre>
<p><em>A logistic regression was performed on to predict the prior therapy variable (y) from the variables of cell type (celltype) and diagnosis time (diagtime). After running the coefficient test, the diagnosis time significantly increases the log-odds of prior therapy observed (y = 1). Controlling for diagnosis time (diagtime), none of the cell types, including squamous, are significantly different. Controlling for cell type (celltype), for every 1-unit increase in diagnosis time (diagtime), odds of prior therapy change by a factor of 1.149 (increasing by 114%). A confusion matrix for the logistic regression was performed to plot model predictions against true values. The proportion of correctly classified cases is the overall accuracy resulting in a value of 0.77. The sensitivity (TPR) values is 0.35, meaning that was the proportion of prior therapy (y = 1) correctly classified. The correctly classified proportion, or specificity (TNR) of no prior therapy (y = 0) is 0.95. The proportion classified as having prior therapy (y = 1) who actually are classified is 0.74. An ROC curve was generated to then calculate the AUC, which is the area under the curve. The purpose of calculating the AUC was to quantify how well the predictions are overall.The AUC that was calculated resulted in a value of 0.814. Because the AUC falls between .8-.9, the AUC value is considered good. The 10-fold CV was performed and the average out-of-sample accuracy is 0.75, average out-of-sample sensitivity is 0.37, and there was not an average out-of-sample recall (ppv = NaN). </em></p>
</div>
<div id="lasso-regression-model" class="section level3">
<h3>6 - LASSO regression model:</h3>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 3.0-2</code></pre>
<pre class="r"><code>fit2 &lt;- glm(y ~ -1 + status + karno + time + celltype + diagtime + age + trt, data = veteran, family = &quot;binomial&quot;)
model.matrix(fit2) %&gt;% head()</code></pre>
<pre><code>##   status karno time celltypesquamous celltypesmallcell celltypeadeno
## 1      1    60   72                1                 0             0
## 2      1    70  411                1                 0             0
## 3      1    60  228                1                 0             0
## 4      1    60  126                1                 0             0
## 5      1    70  118                1                 0             0
## 6      1    20   10                1                 0             0
##   celltypelarge diagtime age trt
## 1             0        7  69   1
## 2             0        5  64   1
## 3             0        3  38   1
## 4             0        9  63   1
## 5             0       11  65   1
## 6             0        5  49   1</code></pre>
<pre class="r"><code>set.seed(1234)
x&lt;-model.matrix(fit2)
x&lt;-scale(x)
y&lt;-as.matrix(veteran$y)
cv&lt;-cv.glmnet(x,y,family=&#39;binomial&#39;)
lasso&lt;-glmnet(x,y,family=&#39;binomial&#39;,lambda=cv$lambda.1se)
coef(cv)</code></pre>
<pre><code>## 11 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                            1
## (Intercept)       -0.8949332
## status             .        
## karno              .        
## time               .        
## celltypesquamous   .        
## celltypesmallcell  .        
## celltypeadeno      .        
## celltypelarge      .        
## diagtime           0.2629170
## age                .        
## trt                .</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
data1&lt;-veteran[sample(nrow(veteran)),]
folds&lt;-cut(seq(1:nrow(veteran)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$y
 fit3&lt;-glm(y~diagtime,data=train,family=&quot;binomial&quot;)
 probs&lt;-predict(fit3,newdata = test,type=&quot;response&quot;)
 diags&lt;-rbind(diags,class_diag(probs,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc      sens      spec ppv       auc
## 1 0.7598901 0.2985714 0.9416162 NaN 0.8076621</code></pre>
<p><em>After the LASSO regression was performed and choosing lambda to give the simplest model whose accuracy is near that of the best, the variable retained was the diagnosis time (diagtime). This is the most important predictors of y.Once the 10-fold CV model was performed, the model’s out-of-sample accuracy is the same as that of the logistic regression in part 5, both with a value of 0.75. </em></p>
</div>
</div>
